import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, writeFileSync, mkdirSync, readFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { injectVersion } from './inject-version.js';

const SHA256_RE = /^sha256:[0-9a-f]{64}$/;

function makeTmpDir(): string {
  return mkdtempSync(join(tmpdir(), 'inject-version-test-'));
}

describe('injectVersion.hashFile', () => {
  let dir: string;

  beforeEach(() => {
    dir = makeTmpDir();
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it('returns sha256: prefix followed by 64 hex chars', () => {
    const f = join(dir, 'a.txt');
    writeFileSync(f, 'hello world');
    const h = injectVersion.hashFile(f);
    expect(h).toMatch(SHA256_RE);
  });

  it('is deterministic — same input gives same hash', () => {
    const f = join(dir, 'a.txt');
    writeFileSync(f, 'deterministic content');
    const h1 = injectVersion.hashFile(f);
    const h2 = injectVersion.hashFile(f);
    expect(h1).toBe(h2);
  });

  it('changes when file content changes', () => {
    const f = join(dir, 'a.txt');
    writeFileSync(f, 'one');
    const h1 = injectVersion.hashFile(f);
    writeFileSync(f, 'two');
    const h2 = injectVersion.hashFile(f);
    expect(h1).not.toBe(h2);
  });
});

describe('injectVersion.hashDirectory', () => {
  let dir: string;

  beforeEach(() => {
    dir = makeTmpDir();
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it('returns sha256: prefix followed by 64 hex chars', () => {
    writeFileSync(join(dir, 'a.txt'), 'a');
    writeFileSync(join(dir, 'b.txt'), 'b');
    const h = injectVersion.hashDirectory(dir);
    expect(h).toMatch(SHA256_RE);
  });

  it('is deterministic — unchanged directory gives same hash', () => {
    writeFileSync(join(dir, 'a.txt'), 'aaa');
    writeFileSync(join(dir, 'b.txt'), 'bbb');
    mkdirSync(join(dir, 'sub'));
    writeFileSync(join(dir, 'sub', 'c.txt'), 'ccc');

    const h1 = injectVersion.hashDirectory(dir);
    const h2 = injectVersion.hashDirectory(dir);
    expect(h1).toBe(h2);
  });

  it('changes when a top-level file content changes', () => {
    writeFileSync(join(dir, 'a.txt'), 'aaa');
    writeFileSync(join(dir, 'b.txt'), 'bbb');
    const h1 = injectVersion.hashDirectory(dir);

    writeFileSync(join(dir, 'a.txt'), 'AAA');
    const h2 = injectVersion.hashDirectory(dir);
    expect(h1).not.toBe(h2);
  });

  it('changes when a nested file is added (recursion check)', () => {
    writeFileSync(join(dir, 'a.txt'), 'aaa');
    mkdirSync(join(dir, 'sub'));
    writeFileSync(join(dir, 'sub', 'existing.txt'), 'x');
    const h1 = injectVersion.hashDirectory(dir);

    mkdirSync(join(dir, 'sub', 'deep'));
    writeFileSync(join(dir, 'sub', 'deep', 'new.txt'), 'new file');
    const h2 = injectVersion.hashDirectory(dir);
    expect(h1).not.toBe(h2);
  });

  // ── Determinism / collision tests (regression anchors) ──
  //
  // The simple "hash an unchanged dir twice" test is tautological — it would
  // pass for any broken hash. The tests below pin down the *load-bearing*
  // properties of hashDirectory (it is consumed by fork detection in Task 5+).

  // Test A — Fixture-anchored hash.
  // Locks the on-disk algorithm: SHA256 of
  //   "a.txt" \0 "AAA" \0 "b/c.txt" \0 "BBB" \0
  // with paths normalised to forward slashes and sorted lexicographically.
  // If anyone changes the algorithm (sort order, separator, normalisation),
  // this constant assertion breaks loudly.
  it('produces the expected hash for a fixed fixture (algorithm anchor)', () => {
    writeFileSync(join(dir, 'a.txt'), 'AAA');
    mkdirSync(join(dir, 'b'));
    writeFileSync(join(dir, 'b', 'c.txt'), 'BBB');

    // Precomputed: see test-helper at top of file. Generated by hand with
    // node -e (NUL-separated `<rel>\0<content>\0` pairs in sorted order).
    const expected =
      'sha256:166c3f7d68308f1e39e5f29bdaac42b779c7784cb4c5b1ea27981e69ad1cce39';
    expect(injectVersion.hashDirectory(dir)).toBe(expected);
  });

  // Test B — NUL separator prevents boundary collisions.
  // Without a NUL between path and content, the byte streams
  //   "ab" + "c"  and  "a" + "bc"
  // collapse to the same input "abc" and would collide.
  it('does not collide on path/content boundary (NUL separator)', () => {
    const dir1 = makeTmpDir();
    const dir2 = makeTmpDir();
    try {
      writeFileSync(join(dir1, 'ab'), 'c');
      writeFileSync(join(dir2, 'a'), 'bc');
      const h1 = injectVersion.hashDirectory(dir1);
      const h2 = injectVersion.hashDirectory(dir2);
      expect(h1).not.toBe(h2);
    } finally {
      rmSync(dir1, { recursive: true, force: true });
      rmSync(dir2, { recursive: true, force: true });
    }
  });

  // Test C — path / content are both folded into the hash.
  // Swapping contents while keeping filenames must change the hash, AND
  // swapping filenames while keeping contents must also change the hash.
  // Either failure means path or content was effectively ignored / mis-ordered.
  it('changes when two files swap contents (filenames fixed)', () => {
    writeFileSync(join(dir, 'x.txt'), 'one');
    writeFileSync(join(dir, 'y.txt'), 'two');
    const h1 = injectVersion.hashDirectory(dir);

    writeFileSync(join(dir, 'x.txt'), 'two');
    writeFileSync(join(dir, 'y.txt'), 'one');
    const h2 = injectVersion.hashDirectory(dir);
    expect(h1).not.toBe(h2);
  });

  it('changes when two files swap filenames (contents fixed)', () => {
    const dirA = makeTmpDir();
    const dirB = makeTmpDir();
    try {
      // dirA: x.txt="one", y.txt="two"
      writeFileSync(join(dirA, 'x.txt'), 'one');
      writeFileSync(join(dirA, 'y.txt'), 'two');
      // dirB: x.txt="two", y.txt="one"  (filenames swapped vs dirA contents)
      writeFileSync(join(dirB, 'x.txt'), 'two');
      writeFileSync(join(dirB, 'y.txt'), 'one');

      expect(injectVersion.hashDirectory(dirA)).not.toBe(
        injectVersion.hashDirectory(dirB),
      );
    } finally {
      rmSync(dirA, { recursive: true, force: true });
      rmSync(dirB, { recursive: true, force: true });
    }
  });

  // Test D — final walk order is independent of stack/readdir traversal order.
  //
  // walkSorted() uses a LIFO stack: without the final `out.sort()` call, two
  // sibling subdirectories would be visited in reverse push-order (`sub_b`
  // before `sub_a`) and the resulting walk would be order-dependent on the
  // LIFO discipline. The trailing sort is what makes hashDirectory truly
  // deterministic for trees with multiple sibling directories. We anchor that
  // property here with a fixture that pre-computes the SHA256 for the *sorted*
  // walk order. If anyone drops `out.sort()`, this test fails because the
  // emitted byte stream becomes `sub_b/y.txt …, sub_a/x.txt …` instead of
  // `sub_a/x.txt …, sub_b/y.txt …`.
  it('produces sorted walk order across sibling subdirectories (final sort anchor)', () => {
    // Layout:
    //   <dir>/root.txt   = "ROOT"
    //   <dir>/sub_a/x.txt = "AX"
    //   <dir>/sub_b/y.txt = "BY"
    // Sorted relative-path walk:
    //   root.txt, sub_a/x.txt, sub_b/y.txt
    writeFileSync(join(dir, 'root.txt'), 'ROOT');
    mkdirSync(join(dir, 'sub_a'));
    writeFileSync(join(dir, 'sub_a', 'x.txt'), 'AX');
    mkdirSync(join(dir, 'sub_b'));
    writeFileSync(join(dir, 'sub_b', 'y.txt'), 'BY');

    // Pre-computed by hand:
    //   sha256( "root.txt"\0"ROOT"\0"sub_a/x.txt"\0"AX"\0"sub_b/y.txt"\0"BY"\0 )
    const expected =
      'sha256:c0e20824cde391aabfbe630698a8c48e0ca032aed38da76fc2781b14205f4fb5';
    expect(injectVersion.hashDirectory(dir)).toBe(expected);
  });

  // Test D' — defensive companion: hash is independent of the *creation
  // order* of files (catches a regression where someone trusts readdir's
  // platform-dependent ordering instead of sorting). On filesystems whose
  // readdir is inode/creation-ordered (Linux ext4), removing the per-dir sort
  // would flip this; on macOS APFS readdir already alphabetises, so this is a
  // best-effort smoke check — Test D above is the strong anchor.
  it('is independent of creation order (defensive)', () => {
    const dir1 = makeTmpDir();
    const dir2 = makeTmpDir();
    try {
      writeFileSync(join(dir1, 'a.txt'), 'A');
      writeFileSync(join(dir1, 'b.txt'), 'B');
      writeFileSync(join(dir1, 'c.txt'), 'C');

      writeFileSync(join(dir2, 'c.txt'), 'C');
      writeFileSync(join(dir2, 'b.txt'), 'B');
      writeFileSync(join(dir2, 'a.txt'), 'A');

      expect(injectVersion.hashDirectory(dir1)).toBe(
        injectVersion.hashDirectory(dir2),
      );
    } finally {
      rmSync(dir1, { recursive: true, force: true });
      rmSync(dir2, { recursive: true, force: true });
    }
  });

  // Test E — negative cases: nonexistent paths surface as errors.
  it('hashFile throws for nonexistent path', () => {
    expect(() =>
      injectVersion.hashFile('/nonexistent-inject-version-test-path/xyz'),
    ).toThrow(/ENOENT/);
  });

  it('hashDirectory throws for nonexistent path', () => {
    expect(() =>
      injectVersion.hashDirectory('/nonexistent-inject-version-test-path/xyz'),
    ).toThrow(/ENOENT/);
  });
});

describe('injectVersion.hashArtifact (file-vs-directory auto-detect)', () => {
  let dir: string;

  beforeEach(() => {
    dir = makeTmpDir();
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it('hashes a regular file (file branch)', () => {
    const f = join(dir, 'single.txt');
    writeFileSync(f, 'one-file');
    const h = injectVersion.hashArtifact('test', f);
    expect(h).toBe(injectVersion.hashFile(f));
    expect(h).toMatch(SHA256_RE);
  });

  it('hashes a directory (directory branch)', () => {
    writeFileSync(join(dir, 'a.txt'), 'a');
    mkdirSync(join(dir, 'sub'));
    writeFileSync(join(dir, 'sub', 'b.txt'), 'b');
    const h = injectVersion.hashArtifact('test', dir);
    expect(h).toBe(injectVersion.hashDirectory(dir));
    expect(h).toMatch(SHA256_RE);
  });

  it('throws for nonexistent path', () => {
    expect(() =>
      injectVersion.hashArtifact('test', '/nonexistent-inject-version-artifact-test'),
    ).toThrow(/ENOENT/);
  });
});

describe('injectVersion.write', () => {
  let dir: string;

  beforeEach(() => {
    dir = makeTmpDir();
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it('writes a _version.ts file with all artifact exports', () => {
    const outPath = join(dir, '_version.ts');
    injectVersion.write(outPath, {
      version: '0.8.0',
      workerPackageVersion: '0.8.0-worker',
      webPackageVersion: '0.8.0-web',
      liffPackageVersion: '0.8.0-liff',
      workerHash: 'sha256:aaaa',
      adminHash: 'sha256:bbbb',
      liffHash: 'sha256:cccc',
      workerAssetsHash: 'sha256:dddd',
      releasedAt: '2026-05-12T03:00:00Z',
    });

    expect(existsSync(outPath)).toBe(true);
    const content = readFileSync(outPath, 'utf8');
    expect(content).toContain('export const BUNDLE_VERSION = "0.8.0"');
    expect(content).toContain('export const WORKER_PACKAGE_VERSION = "0.8.0-worker"');
    expect(content).toContain('export const WEB_PACKAGE_VERSION = "0.8.0-web"');
    expect(content).toContain('export const LIFF_PACKAGE_VERSION = "0.8.0-liff"');
    expect(content).toContain('export const WORKER_HASH = "sha256:aaaa"');
    expect(content).toContain('export const ADMIN_HASH = "sha256:bbbb"');
    expect(content).toContain('export const LIFF_HASH = "sha256:cccc"');
    expect(content).toContain('export const WORKER_ASSETS_HASH = "sha256:dddd"');
    expect(content).toContain('export const RELEASED_AT = "2026-05-12T03:00:00Z"');
  });
});
