#!/usr/bin/env tsx
/**
 * Build-time hash injection.
 *
 * Computes SHA256 of the worker bundle, admin static output and LIFF dist,
 * then writes `apps/worker/src/_version.ts` so the Worker runtime can expose
 * `/_version` for self-diagnostics, upgrade-flow checks and rollback hints.
 *
 * Library API (`injectVersion`):
 *   - hashFile(path)      → "sha256:<hex>"
 *   - hashDirectory(dir)  → "sha256:<hex>"   (deterministic, recursive)
 *   - write(outPath, v)   → writes _version.ts
 *
 * CLI:
 *   tsx inject-version.ts \
 *     --version 0.8.0 \
 *     --worker dist/index.js \
 *     --admin ../web/out \
 *     --liff ../liff/dist \
 *     --out src/_version.ts
 *
 * Prints `{ workerHash, adminHash, liffHash }` JSON to stdout so GH Actions
 * can pipe it into the manifest generator.
 */

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { argv, exit, stderr, stdout } from 'node:process';

export interface VersionData {
  version: string;
  workerPackageVersion: string;
  webPackageVersion: string;
  liffPackageVersion: string;
  workerHash: string;
  adminHash: string;
  liffHash: string;
  workerAssetsHash: string;
  releasedAt: string;
}

function hashFile(filePath: string): string {
  const content = readFileSync(filePath);
  const digest = createHash('sha256').update(content).digest('hex');
  return `sha256:${digest}`;
}

function walkSorted(root: string): string[] {
  // Recursive lexicographic walk. Returns absolute paths of regular files.
  const out: string[] = [];
  const stack: string[] = [root];
  while (stack.length > 0) {
    const current = stack.pop() as string;
    const entries = readdirSync(current).sort();
    for (const name of entries) {
      const full = join(current, name);
      const st = statSync(full);
      if (st.isDirectory()) {
        stack.push(full);
      } else if (st.isFile()) {
        out.push(full);
      }
      // symlinks / sockets etc. are ignored on purpose — bundle outputs should
      // never contain them, and including them would make hashes platform-dependent.
    }
  }
  // Sort by path so push-order from the stack (LIFO across subdirs) does not
  // affect determinism.
  out.sort();
  return out;
}

function hashDirectory(dir: string): string {
  const files = walkSorted(dir);
  const hash = createHash('sha256');
  const NUL = Buffer.from([0]);
  for (const file of files) {
    // Normalise path separators so Windows ↔ POSIX builds produce the same hash.
    const rel = relative(dir, file).split(sep).join('/');
    hash.update(Buffer.from(rel, 'utf8'));
    hash.update(NUL);
    hash.update(readFileSync(file));
    hash.update(NUL);
  }
  return `sha256:${hash.digest('hex')}`;
}

function write(outPath: string, v: VersionData): void {
  const body = [
    '// AUTO-GENERATED by scripts/inject-version.ts — DO NOT EDIT.',
    '// Regenerated on every build; values reflect the artifacts being shipped.',
    '',
    `export const BUNDLE_VERSION = ${JSON.stringify(v.version)};`,
    `export const WORKER_PACKAGE_VERSION = ${JSON.stringify(v.workerPackageVersion)};`,
    `export const WEB_PACKAGE_VERSION = ${JSON.stringify(v.webPackageVersion)};`,
    `export const LIFF_PACKAGE_VERSION = ${JSON.stringify(v.liffPackageVersion)};`,
    `export const WORKER_HASH = ${JSON.stringify(v.workerHash)};`,
    `export const ADMIN_HASH = ${JSON.stringify(v.adminHash)};`,
    `export const LIFF_HASH = ${JSON.stringify(v.liffHash)};`,
    `export const WORKER_ASSETS_HASH = ${JSON.stringify(v.workerAssetsHash)};`,
    `export const RELEASED_AT = ${JSON.stringify(v.releasedAt)};`,
    '',
  ].join('\n');
  writeFileSync(outPath, body, 'utf8');
}

export const injectVersion = {
  hashFile,
  hashDirectory,
  hashArtifact,
  write,
};

// ─── CLI entry ────────────────────────────────────────────────────────────────

interface CliArgs {
  version?: string;
  workerPackageVersion?: string;
  webPackageVersion?: string;
  liffPackageVersion?: string;
  worker?: string;
  admin?: string;
  liff?: string;
  workerAssets?: string;
  out?: string;
  releasedAt?: string;
}

function parseArgs(args: string[]): CliArgs {
  const out: CliArgs = {};
  for (let i = 0; i < args.length; i += 1) {
    const a = args[i];
    if (!a.startsWith('--')) continue;
    const key = a.slice(2);
    const value = args[i + 1];
    if (value === undefined || value.startsWith('--')) {
      stderr.write(`inject-version: missing value for --${key}\n`);
      exit(2);
    }
    i += 1;
    switch (key) {
      case 'version':
        out.version = value;
        break;
      case 'worker-package-version':
        out.workerPackageVersion = value;
        break;
      case 'web-package-version':
        out.webPackageVersion = value;
        break;
      case 'liff-package-version':
        out.liffPackageVersion = value;
        break;
      case 'worker':
        out.worker = value;
        break;
      case 'admin':
        out.admin = value;
        break;
      case 'liff':
        out.liff = value;
        break;
      case 'worker-assets':
      case 'workerAssets':
        out.workerAssets = value;
        break;
      case 'out':
        out.out = value;
        break;
      case 'released-at':
      case 'releasedAt':
        out.releasedAt = value;
        break;
      default:
        stderr.write(`inject-version: unknown flag --${key}\n`);
        exit(2);
    }
  }
  return out;
}

function requireArg<T extends keyof CliArgs>(args: CliArgs, key: T): NonNullable<CliArgs[T]> {
  const v = args[key];
  if (v === undefined) {
    stderr.write(`inject-version: --${String(key)} is required\n`);
    exit(2);
  }
  return v as NonNullable<CliArgs[T]>;
}

function hashArtifact(label: string, p: string): string {
  const st = statSync(p);
  if (st.isDirectory()) return hashDirectory(p);
  if (st.isFile()) return hashFile(p);
  throw new Error(`inject-version: ${label} path is neither file nor directory: ${p}`);
}

function main(rawArgs: string[]): void {
  const args = parseArgs(rawArgs);
  const version = requireArg(args, 'version');
  const workerPackageVersion = requireArg(args, 'workerPackageVersion');
  const webPackageVersion = requireArg(args, 'webPackageVersion');
  const liffPackageVersion = requireArg(args, 'liffPackageVersion');
  const workerPath = requireArg(args, 'worker');
  const adminPath = requireArg(args, 'admin');
  const liffPath = requireArg(args, 'liff');
  const workerAssetsPath = requireArg(args, 'workerAssets');
  const outPath = requireArg(args, 'out');
  const releasedAt = args.releasedAt ?? new Date().toISOString();

  const workerHash = hashArtifact('worker', workerPath);
  const adminHash = hashArtifact('admin', adminPath);
  const liffHash = hashArtifact('liff', liffPath);
  const workerAssetsHash = hashArtifact('worker-assets', workerAssetsPath);

  write(outPath, {
    version,
    workerPackageVersion,
    webPackageVersion,
    liffPackageVersion,
    workerHash,
    adminHash,
    liffHash,
    workerAssetsHash,
    releasedAt,
  });

  stdout.write(
    JSON.stringify({
      version,
      workerPackageVersion,
      webPackageVersion,
      liffPackageVersion,
      workerHash,
      adminHash,
      liffHash,
      workerAssetsHash,
      releasedAt,
    }) + '\n',
  );
}

// Run when invoked as a script (works whether tsx/ts-node loaders rewrite
// the URL or not).
const isCliEntry = (() => {
  if (!argv[1]) return false;
  try {
    return fileURLToPath(import.meta.url) === argv[1];
  } catch {
    return false;
  }
})();

if (isCliEntry) {
  main(argv.slice(2));
}
