import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { afterEach, describe, expect, it, vi } from 'vitest';

const { execaMock, repoPnpmMock } = vi.hoisted(() => ({
  execaMock: vi.fn(),
  repoPnpmMock: vi.fn(),
}));

vi.mock('execa', () => ({ execa: execaMock }));
vi.mock('../src/lib/pnpm.js', () => ({ repoPnpm: repoPnpmMock }));

import {
  ensureRepo,
  pinRepoToTag,
} from '../src/steps/clone-repo.js';
import { renderInstalledWranglerToml } from '../src/lib/installed-wrangler.js';

const originalCwd = process.cwd();

afterEach(() => {
  vi.restoreAllMocks();
  vi.unstubAllEnvs();
  execaMock.mockReset();
  repoPnpmMock.mockReset();
  process.chdir(originalCwd);
});

function setupHome(wranglerToml: string, config?: object): string {
  const home = mkdtempSync(join(tmpdir(), 'line-harness-f17-home-'));
  const repo = join(home, '.line-harness');
  mkdirSync(join(repo, 'apps/worker'), { recursive: true });
  writeFileSync(join(repo, 'pnpm-workspace.yaml'), 'packages: []\n');
  writeFileSync(join(repo, 'apps/worker/wrangler.toml'), wranglerToml);
  if (config) writeFileSync(join(repo, '.line-harness-config.json'), JSON.stringify(config));
  vi.stubEnv('HOME', home);
  vi.spyOn(process, 'cwd').mockReturnValue(join(home, 'outside'));
  return repo;
}

describe('clone-repo safety', () => {
  it('does not reset a custom checkout before pinning a tag', async () => {
    const repo = mkdtempSync(join(tmpdir(), 'line-harness-f17-custom-'));
    mkdirSync(join(repo, 'apps/worker'), { recursive: true });
    const wranglerPath = join(repo, 'apps/worker/wrangler.toml');
    const customToml = '# customer-owned\nname = "custom"\n';
    writeFileSync(wranglerPath, customToml);
    execaMock.mockImplementation(async (_file: string, args: string[]) => {
      if (args[0] === 'checkout' && args[1] === '--quiet') return {};
      return { stdout: '', stderr: '' };
    });
    repoPnpmMock.mockResolvedValue(undefined);

    await pinRepoToTag(repo, '1.2.3');

    expect(execaMock.mock.calls.map(([file, args]) => [file, args])).not.toContainEqual([
      'git', ['checkout', '--', 'apps/worker/wrangler.toml'],
    ]);
    expect(readFileSync(wranglerPath, 'utf8')).toBe(customToml);
  });

  it('does not treat only the generated marker as permission to reset the canonical checkout', async () => {
    const toml = '# Generated by create-line-harness. Safe to overwrite on future setup runs.\n';
    const repo = setupHome(toml);
    execaMock.mockResolvedValue({ stdout: '', stderr: '' });

    await expect(ensureRepo(null)).resolves.toBe(repo);

    expect(execaMock.mock.calls.map(([file, args]) => [file, args])).not.toContainEqual([
      'git', ['checkout', '--', 'apps/worker/wrangler.toml'],
    ]);
    expect(readFileSync(join(repo, 'apps/worker/wrangler.toml'), 'utf8')).toBe(toml);
  });

  it('does not reset an exact generated config when the file is staged', async () => {
    const config = {
      projectName: 'line-harness',
      workerName: 'line-harness',
      accountId: 'account',
      d1DatabaseId: 'database-id',
      d1DatabaseName: 'line-harness',
      r2BucketName: 'line-harness-images',
      workerPublicUrl: 'https://worker.example',
      adminProject: 'admin',
      adminPublicUrl: 'https://admin.pages.dev',
      workerDeployMode: 'source',
    };
    const toml = renderInstalledWranglerToml({
      workerName: 'line-harness', accountId: 'account', d1DatabaseName: 'line-harness',
      d1DatabaseId: 'database-id', r2BucketName: 'line-harness-images',
      workerPublicUrl: 'https://worker.example', adminPagesProject: 'admin',
      adminPublicUrl: 'https://admin.pages.dev', liffPagesProject: '',
      liffPublicUrl: 'https://worker.example', manifestUrl: 'https://example/manifest.json',
      workerDeployMode: 'source',
    });
    const repo = setupHome(toml, config);
    execaMock.mockImplementation(async (_file: string, args: string[]) => {
      if (args[0] === 'diff' && args[1] === '--cached') {
        throw new Error('staged');
      }
      return { stdout: '', stderr: '' };
    });

    await expect(ensureRepo(null)).resolves.toBe(repo);

    expect(execaMock.mock.calls.map(([file, args]) => [file, args])).not.toContainEqual([
      'git', ['checkout', '--', 'apps/worker/wrangler.toml'],
    ]);
    expect(readFileSync(join(repo, 'apps/worker/wrangler.toml'), 'utf8')).toBe(toml);
  });

  it('keeps the canonical setup path able to restore an exact unstaged generated config', async () => {
    const config = {
      projectName: 'line-harness', workerName: 'line-harness', accountId: 'account',
      d1DatabaseId: 'database-id', d1DatabaseName: 'line-harness',
      r2BucketName: 'line-harness-images', workerPublicUrl: 'https://worker.example',
      adminProject: 'admin', adminPublicUrl: 'https://admin.pages.dev',
      manifestUrl: 'https://example/manifest.json', workerDeployMode: 'source',
    };
    const toml = renderInstalledWranglerToml({
      workerName: 'line-harness', accountId: 'account', d1DatabaseName: 'line-harness',
      d1DatabaseId: 'database-id', r2BucketName: 'line-harness-images',
      workerPublicUrl: 'https://worker.example', adminPagesProject: 'admin',
      adminPublicUrl: 'https://admin.pages.dev', liffPagesProject: '',
      liffPublicUrl: 'https://worker.example', manifestUrl: 'https://example/manifest.json',
      workerDeployMode: 'source',
    });
    const repo = setupHome(toml, config);
    execaMock.mockResolvedValue({ stdout: '', stderr: '' });

    await expect(ensureRepo(null)).resolves.toBe(repo);

    expect(execaMock.mock.calls.map(([file, args]) => [file, args])).toContainEqual([
      'git', ['diff', '--cached', '--quiet', '--', 'apps/worker/wrangler.toml'],
    ]);
    expect(execaMock.mock.calls.map(([file, args]) => [file, args])).toContainEqual([
      'git', ['checkout', '--', 'apps/worker/wrangler.toml'],
    ]);
  });
});
