const GENERATED_MARKER = '# Generated by create-line-harness. Safe to overwrite on future setup runs.';

const DEFAULT_MANIFEST_URL =
  'https://github.com/Shudesu/line-harness-oss/releases/latest/download/release-manifest.json';

export interface SavedInstallConfig {
  projectName?: string;
  workerName?: string;
  adminProject?: string;
  adminUrl?: string;
  workerUrl?: string;
  d1DatabaseId?: string;
  d1DatabaseName?: string;
  r2BucketName?: string;
  accountId?: string;
  cfAccountId?: string;
  manifestUrl?: string;
  workerPublicUrl?: string;
  adminPublicUrl?: string;
  liffProject?: string;
  liffPublicUrl?: string;
  /**
   * 'bundle' — Worker deployed from the official release bundle
   * (main = dist/release/index.js + no_bundle, version-stamped).
   * 'source' / absent — legacy install built from src/index.ts.
   */
  workerDeployMode?: 'bundle' | 'source';
  /** Release version deployed by setup/adoption (informational). */
  installedVersion?: string;
}

export interface InstalledWranglerConfig {
  workerName: string;
  accountId: string;
  d1DatabaseName: string;
  d1DatabaseId: string;
  r2BucketName: string;
  workerPublicUrl: string;
  adminPagesProject: string;
  adminPublicUrl: string;
  /** '' = worker-assets install (no LIFF Pages project). */
  liffPagesProject: string;
  liffPublicUrl: string;
  manifestUrl: string;
  workerDeployMode: 'bundle' | 'source';
}

export function isGeneratedInstalledWranglerToml(content: string): boolean {
  return content.includes(GENERATED_MARKER);
}

export function resolveInstalledWranglerConfig(config: SavedInstallConfig): InstalledWranglerConfig | null {
  const workerName = config.workerName ?? config.projectName;
  const accountId = config.cfAccountId ?? config.accountId;
  const d1DatabaseId = config.d1DatabaseId;
  const d1DatabaseName = config.d1DatabaseName ?? config.projectName;
  const r2BucketName = config.r2BucketName ?? (config.projectName ? `${config.projectName}-images` : undefined);
  const workerPublicUrl = config.workerPublicUrl ?? config.workerUrl;

  let adminPagesProject = config.adminProject;
  if (!adminPagesProject && typeof config.adminUrl === 'string') {
    try {
      adminPagesProject = new URL(config.adminUrl).hostname.replace(/\.pages\.dev$/, '');
    } catch {
      // Ignore parse errors and fall through to null.
    }
  }

  const adminPublicUrl = config.adminPublicUrl ?? config.adminUrl;
  // Worker-assets installs have no LIFF Pages project — '' tells the
  // worker-side self-update to skip every LIFF Pages step. (The old
  // `${workerName}-liff` fallback pointed self-update at a project that
  // was never created and made its LIFF deploy step fail.)
  const liffPagesProject = config.liffProject ?? '';
  const liffPublicUrl = config.liffPublicUrl ?? workerPublicUrl;

  if (
    !workerName ||
    !accountId ||
    !d1DatabaseId ||
    !d1DatabaseName ||
    !r2BucketName ||
    !workerPublicUrl ||
    !adminPagesProject ||
    !adminPublicUrl ||
    !liffPublicUrl
  ) {
    return null;
  }

  return {
    workerName,
    accountId,
    d1DatabaseName,
    d1DatabaseId,
    r2BucketName,
    workerPublicUrl,
    adminPagesProject,
    adminPublicUrl,
    liffPagesProject,
    liffPublicUrl,
    manifestUrl: config.manifestUrl ?? DEFAULT_MANIFEST_URL,
    workerDeployMode: config.workerDeployMode === 'bundle' ? 'bundle' : 'source',
  };
}

export function renderInstalledWranglerToml(config: InstalledWranglerConfig): string {
  // Bundle installs deploy the official release artifact byte-for-byte:
  // `no_bundle` stops wrangler from re-bundling (which would invalidate the
  // version stamp's honesty), and the artifact path is refreshed by
  // setup/update so a manual `wrangler deploy` re-ships the same release.
  const mainSection =
    config.workerDeployMode === 'bundle' ? `main = "dist/release/index.js"\nno_bundle = true` : `main = "src/index.ts"`;

  return `${GENERATED_MARKER}
name = "${config.workerName}"
${mainSection}
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
account_id = "${config.accountId}"

# Worker runs before static assets so bot UAs get OGP HTML injection;
# normal UAs fall through to the SPA via env.ASSETS.fetch().
[assets]
directory = "dist/client"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "${config.d1DatabaseName}"
database_id = "${config.d1DatabaseId}"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "${config.r2BucketName}"

[triggers]
crons = ["*/5 * * * *", "0 */6 * * *"]

[vars]
WORKER_NAME = "${config.workerName}"
ADMIN_PAGES_PROJECT = "${config.adminPagesProject}"
LIFF_PAGES_PROJECT = "${config.liffPagesProject}"
D1_DATABASE_ID = "${config.d1DatabaseId}"
MANIFEST_URL = "${config.manifestUrl}"
WORKER_PUBLIC_URL = "${config.workerPublicUrl}"
ADMIN_PUBLIC_URL = "${config.adminPublicUrl}"
LIFF_PUBLIC_URL = "${config.liffPublicUrl}"
CF_ACCOUNT_ID = "${config.accountId}"
`;
}
